# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 11:42
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=0.0, max_length=63),
        ),
    ]
