# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 11:48
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_hotel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
